### ISSUE TITLE
Question about process_ABCD_mTBI.sh

### ISSUE THREAD

**Issue by fullcream9** [GuidoGuberman/Multi-tract-multi-symptom-relationships-in-pediatric-concussion#2]
Dear all,

https://github.com/GuidoGuberman/Multi-tract-multi-symptom-relationships-in-pediatric-concussion/blob/0ecae92dfcbb60e9d6f64477776155746aa5ac8c/process_ABCD_mTBI.sh#L16

1. Is "~/scratch/data/ABCD_mTBI_data_complete" the output of executing MasterScript.sh? Thanks in advance
2. No script calls process_ABCD_mTBI.sh? We need to execute process_ABCD_mTBI.sh separately.

Best regards,
Panshi.

**Comment by GuidoGuberman** [comment]
Dear Panshi,

Thanks for your questions. Yes, ABCD_mTBI_data_Complete should be the output of executing MasterScript.sh. The part that is missing is that the MasterScript was executed locally, whereas process_ABCD_mTBI.sh is executed on a ComputeCanada server. So after MasterScript is executed, the data is transferred to the server. That brings me to your second question. Yes, process_ABCD_mTBI.sh is executed on its own, on a ComputeCanada cluster (or a cluster of your choice). This is the script that calls Tractoflow. 

Hope this helps!
Guido.

**Comment by fullcream9** [comment]
Thanks for your response, that was very clear and useful!
